# Generated by Django 5.1 on 2024-08-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='profile_picture',
            field=models.URLField(default=''),
        ),
    ]
